### ISSUE TITLE
Control where styles are injected

### ISSUE THREAD

**Issue by hernansartorio** [vercel-labs/react-tweet#83]
Hi, thanks for making this. I need to render tweets within a controlled iframe, and manually inject the CSS for any elements in it, however the library is injecting the CSS Modules styles on the main document, is there any workaround for this?

**Comment by lfades** [comment]
The library itself doesn't export its styles, it's up to the bundler where it's used to build and export them. So the library is not injecting any styles but your bundler and that's something you can customize in the bundler itself.

Let me know if you have any questions. If the components exported by the library don't work for you I'll be allowing it to be fully customizable so that you can create your own components: https://github.com/vercel-labs/react-tweet/pull/86

**Comment by hernansartorio** [comment]
I see, makes sense, thank you for your answer. For now I went with a custom solution but I’ll be following that issue.
